### ISSUE TITLE
NO matter what i fill in, i get 

### ISSUE THREAD

**Issue by DarthKeizer** [srcecde/facebook-bot#4]
python D:\Software\facebook-bot-master\fb_bot.py --a status --u h************@gmail.com --p ************* --url https://www.facebook.com/**********
Invalid parameter
It should be status or likes

Any help, since I tested status and like and I still get the same error

**Comment by srcecde** [comment]
You need to pass --a=status --u=username --p=password. You are missing '=' in parameters.

**Comment by DarthKeizer** [comment]
Just tried it:

`python /facebook-bot/fb_bot.py --a=status --u=h*********.com --p=******** --url=******`
Invalid parameter
It should be status or likes

**Comment by srcecde** [comment]
Hi,

It is working fine. Just a quick question. 
Are you closing the chrome window that is opened after running the bot? If yes then it will return this error.

If you don't want the browser to open then uncomment these two line from bot 
# display = Display(visible=0)
# display.start()

if still issue persist let me know or i can help you with teamviewer.

Here is the quick screenshot i took just now.
@DarthKeizer 
![screenshot from 2017-03-27 11 39 49](https://cloud.githubusercontent.com/assets/18462032/24343404/ee3b77d4-12e3-11e7-8d68-4c4ad28ed53e.png)

**Comment by DarthKeizer** [comment]
@srcecde Hey man just uncommented it and it still gives the same error message. I am using chromium browser tho

**Comment by DarthKeizer** [comment]
@srcecde You there brah?

**Comment by srcecde** [comment]
I can help sorting the issue you are facing with a teamviewer session.

**Comment by DarthKeizer** [comment]
I give up man, I cant figure out why it does not work and a teamviewer session I am not that comfortable with. Thanks for the help anyway :+1:
